title:            SilasQ.com
description:      "The home of Silas Quinnelly"
disqus_shortname: silasq
reading_time:     true
words_per_minute: 200
# Your site's domain goes here (eg: //mmistakes.github.io, http://mademistakes.com, etc)
# When testing locally leave blank or use http://localhost:4000
url: //silasq.com

# Owner/author information
owner:
  name:           Quinnelly's
  avatar:         avatar.jpg
  bio:            
  email:          
  # Social networking links used in footer. Update and remove as you like.
  twitter:        
  facebook:       
  github:         
  stackexchange:  
  linkedin:       
  instagram:      
  flickr:         
  tumblr:         
  # For Google Authorship https://plus.google.com/authorship
  # google plus id, include the '+', eg +mmistakes
  google_plus:    

subject:
  name:         Silas Quinnelly
  bio:          "My name is Silas Quinnelly. I'm but a wee little lad, and my parents wanted me to have a Tumblog so that they could post all the cute things I did while growing up and share with friends & family. Also to show & embarrass me later in life."
  twitter:        SilasQuinnelly

dad:
  name:           Travis Quinnelly
  avatar:         avatar.jpg
  bio:            
  email:          
  # Social networking links used in footer. Update and remove as you like.
  twitter:        TQuizzle
  facebook:       tquinnelly
  github:         tquizzle
  stackexchange:  
  linkedin:       tquinnelly
  instagram:      tquinnelly
  flickr:         
  tumblr:         

mom:
  name:           Heather Quinnelly
  avatar:         avatar.jpg
  bio:            
  email:          
  # Social networking links used in footer. Update and remove as you like.
  twitter:        HQuizzle
  facebook:       hquinnelly
  github:         
  stackexchange:  
  linkedin:       
  instagram:      hquinnelly
  flickr:         
  tumblr:         


# Background image to be tiled on all pages
background: 

# Analytics and webmaster tools stuff goes here
google_analytics:   UA-253329-11
google_verify:      
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:         

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:    America/Chicago
future:      true
highlighter: pygments
markdown:    kramdown
gems:
  - jekyll-sitemap
sass:
  sass_dir: _sass
  style: compressed

# https://github.com/mojombo/jekyll/wiki/Permalinks
permalink:   /:title/

# Amount of post to show on home page
paginate: 10

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: true

  coderay:
    coderay_line_numbers: nil
    coderay_line_numbers_start: 1
    coderay_tab_width: 4
    coderay_bold_every: 10
    coderay_css: class

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "Gemfile", "Gemfile.lock", "README.md", "LICENSE", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules"]